#!/usr/bin/env python3.10
import click
from subprocess import call
import shlex
from time import time

def run(s: str):
    call(shlex.split(s))


@click.command()
@click.argument('message')
@click.opt
def cmd(message: str, meta: bool):
    with open("version", "r") as f:
        version = f.read().strip().split(".")
    if meta:
        version[2] = f'{p}-{int(pr) + 1}'
    else:
        version[2] = f'{int((patch.split("-")[0])) + 1}-0'
    version = ".".join(version)
    with open("version", "w") as f:
        f.write(version)
    run("git add .")
    run(f"git commit -am '{message}{f', bump to `{mmp}`' if not meta else ''}'")
    run("git push")


cmd()

