name: Providers

on:
  push:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Setup
      run: python -m pip install -r requirements.txt
    - name: Run ping.py
      env:
        KV: ${{ secrets.kv }}
      run: |
        python main.py $KV